import type { Metadata } from 'next'
import * as React from 'react'

import { Inter } from 'next/font/google'
import './globals.css'

import { ThemeProvider } from '@/components/theme-provider'
import { NextUIProvider } from '@nextui-org/react'
import { NavBar } from '@/components/nav-bar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <NextUIProvider>
            <main>
              <NavBar />
              {children}
            </main>
          </NextUIProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
